# Generated by Django 2.2 on 2019-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='douban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('quote', models.CharField(blank=True, max_length=255, null=True)),
                ('people', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'douban',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='jingdong',
        ),
    ]
